### ISSUE TITLE
Closed Actions not working

### ISSUE THREAD

**Issue by 1joeljohnson** [Codectory/AutoHDR#38]
I set an App Start Action to change resolution to 3840X1620 and activate HDR on launch of a UWP app.  I then set an App Closed Action to try and deactivate the HDR and set resolution back to 3840X2160.  When launched HDR gets activated and resolution changed; however, when application is closed the HDR does not get deactivated and the resolution does not change back to 3840X2160. 
![autohdrProfile](https://user-images.githubusercontent.com/29613786/143280045-217ce3ae-76cd-4b89-a1b9-61c5acf5d1f5.png)

Attaching log file as well.  

Thank
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7597375/AutoHDR.log)
s

**Comment by Codectory** [comment]
Could you please send me you UserSettings.xml?

**Comment by 1joeljohnson** [comment]
[UserSettings.txt](https://github.com/Codectory/AutoHDR/files/7597830/UserSettings.txt)
Here you go.  
Thank you for the quick response.  I love this application.  I bought you a beer.

**Comment by Codectory** [comment]
Thanks for the beer 👍

**Comment by Codectory** [comment]
Alright, there are some bad things I have done with the UserSettings, a I have to clean this up.

**Comment by 1joeljohnson** [comment]
I'm glad you were able to identify the issue/issues. 

Let me know if there is anything I can help test.

**Comment by Codectory** [comment]
Could you try this with the newest release ?

**Comment by 1joeljohnson** [comment]
Absolutely.

**Comment by kyotocafe** [comment]
With the new version, 1.7.2 , the resolution is changing when the application is closed, however HDR does not get deactivated.

**Comment by Codectory** [comment]
Could you show me your settings file?

kyotocafe ***@***.***> schrieb am Fr. 26. Nov. 2021 um 21:47:

**Comment by kyotocafe** [comment]
Sure, thanks for checking into this, this is my settings file, 
[UserSettings.xml.txt](https://github.com/Codectory/AutoHDR/files/7610661/UserSettings.xml.txt)

**Comment by Codectory** [comment]
Did created an application closed action to disable hdr?

kyotocafe ***@***.***> schrieb am Fr. 26. Nov. 2021 um 21:51:

**Comment by kyotocafe** [comment]
I did try it, but it was the same behaviour as the lost focus actions.

**Comment by Codectory** [comment]
Are you able to toggle HDR with the button on the first page?

kyotocafe ***@***.***> schrieb am Fr. 26. Nov. 2021 um 22:15:

**Comment by kyotocafe** [comment]
Yes, that works fine , it toggles HDR on and off.

**Comment by 1joeljohnson** [comment]
> Could you try this with the newest release ?

This is still not working for me.  When launching Halo Infinite, HDR gets activated and resolution changed to 3840x1620 and when exiting the game, HDR doesnt get deactivated and resolution does not change to 3840x2160.
[UserSettings - Copy.xml.txt](https://github.com/Codectory/AutoHDR/files/7611796/UserSettings.-.Copy.xml.txt)

**Comment by Codectory** [comment]
Should be fixed in 1.7.3

**Comment by 1joeljohnson** [comment]
> Should be fixed in 1.7.3

I'm sorry but this seemed to have broken a few things.  So HDR gets activated and when I launch the application and then it will deactivate HDR when the app is loaded.  Confirmed by my screens settings that HDR got deactivated.
[UserSettings - Copy.xml.txt](https://github.com/Codectory/AutoHDR/files/7626147/UserSettings.-.Copy.xml.txt)
vated.  
Also, the resolution still will not change back to 3840x2160 from being changed to 3840x162.

**Comment by 1joeljohnson** [comment]
Finally got the new json settings to write to folder.  Resolution was to install version 1.7.2, launch it, close it, and then overwrite that with 1.74.  I can now see the user settings json file. 

However, issues still stand with HDR getting deactivated after launch and resolution not changing back after app is closed. 
[AutoHDR.log](https://github.com/Codectory/AutoHDR/files/7626800/AutoHDR.log)


[UserSettings - Copy.json.txt](https://github.com/Codectory/AutoHDR/files/7626806/UserSettings.-.Copy.json.txt)

**Comment by Codectory** [comment]
Can you try to run the app with admin rights?

**Comment by 1joeljohnson** [comment]
> Can you try to run the app with admin rights?

Just tied and same results. HDR gets turned on, religion changes, then HDR gets deactivated when the game is loading. Then when I exit the game, resolution does not change back.

**Comment by Codectory** [comment]
Alright, so the game uses a launcher and this launcher starts the game
process and closes afterwards. AutoHDR works correctly but is monitoring
the wrong process. Can you try another game?

Joel ***@***.***> schrieb am Do. 2. Dez. 2021 um 13:35:

**Comment by 1joeljohnson** [comment]
I tried another game and HDR seems to work but the resolution will still not change back after the app is closed.

**Comment by kyotocafe** [comment]
It is working fine now for me, thanks!

**Comment by 1joeljohnson** [comment]
Another new behavior is that HDR will activate but my resolution will not change for the game I launch. If I alt tab out I can see my desktop resolution and aspect ratio changed but not the game.  

Maybe my use cases don't play well with these features.

**Comment by Codectory** [comment]
The game needs to use the system resolution. If the resolution gets
overwritten in the game settings, AutoHDR can do nothing.

Joel ***@***.***> schrieb am Fr. 3. Dez. 2021 um 00:39:
